### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by kba**
* Add Linux install instructions
* Table of Contents
* Do not use absolute path to kraken in Demo_2

### CODE REVIEW

**Review by wrznr — APPROVED** [review]
Many thanks! Great work.

**Comment by wrznr** [comment]
@cneud Can you have a look?

**Review by cneud — COMMENTED** [review]
Is it safe to rely on $PATH here, i.e. does kraken automatically set this during install (e.g. also on Windows)?

**Comment by kba** [comment]
IIRC (no windows machine to test), `pip` will install executables to a `C:\PythonXX\Scripts` directory under Windows. If users haven't added that location to their `%PATH%`, then no, it won't work. Maybe newer Python installers do that already?

But if kraken isn't on `%PATH%`/`$PATH`, path to binary must be specified anyway, also for tesseract, scantailor-cli etc.

**Comment by cneud** [comment]
True. We may want to add some instructions on setting the environment in the readme later on, since basically it should be possible to run this workflow on both platforms (of course this becomes obsolete once there is a wrapper too).

**Pull request merged**
